version: "3.9"

services:
  app:
    container_name: line-cms-back-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/var/www/line/cms

  web:
    container_name: line-cms-back-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/line/cms

  db:
    container_name: line-cms-back-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 13360:3306
    environment:
      MYSQL_DATABASE: line_db
      MYSQL_USER: baritech
      MYSQL_PASSWORD: baritech
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
      
volumes:
  mysql-volume:
    external:
      name: line-db_volume